version: '3.9'
services:
  haproxy:
    image: haproxy:3.0-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 5432:5432
      - 1111:80
    networks:
      - mynet
  simple_server:
    build: ./server
    depends_on:
      haproxy:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - mynet
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      - mynet
networks:
  mynet:
    name: mynet
    driver: bridge
volumes:
  db_data:
  
  